export { default as PedidosPanel } from "./PedidosPanel";
export type { SupplierOrder } from "./PedidosPanel";
export { default as StockBajoPanel } from "./StockBajoPanel";
export type { ReplenishmentResponse, ReplenishmentProduct } from "./StockBajoPanel";
export { default as SugerenciasPanel } from "./SugerenciasPanel";
export { default as RecepcionPanel } from "./RecepcionPanel";
export { default as PreciosPanel } from "./PreciosPanel";
export { default as RevisionPanel } from "./RevisionPanel";
export { default as ReglaVentaWeb } from "./ReglaVentaWeb";
export { default as AprendizajePanel } from "./AprendizajePanel";
